x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

x-common-env: &common-env
  ENVIRONMENT: ${MOD:-development}
  LOG_LEVEL: ${LOG_LEVEL:-INFO}
  REDIS_URL: redis://redis:6379
  REDIS_PASSWORD: ${REDIS_PASSWORD:-redis123}
  API_GATEWAY_URL: http://api-gateway:8000
  POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
  POSTGRES_PORT: ${POSTGRES_PORT:-5432}
  POSTGRES_USER: ${POSTGRES_USER:-admin}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}

services:  
  postgres:
    image: postgres:16-alpine
    container_name: taskflow-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *default-logging
    networks:
      - taskflow-network

    
  redis:
    image: redis:7-alpine
    container_name: taskflow-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis123}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redis123}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    logging: *default-logging
    networks:
      - taskflow-network

  api_gateway:
    build:
      context: .
      dockerfile: ./docker/python-service.Dockerfile
      args:
        APP_NAME: api_gateway
    container_name: taskflow-api-gateway
    ports:
      - "8000:8000"
    environment:
      <<: *common-env
      USER_URL: http://user-service:8000
      TASK_URL: http://task-service:8000
      NOTIFICATION_URL: http://notification-service:8000
      ANALYTICS_URL: http://analytics-service:8000      
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./apps/api_gateway:/app/apps/api_gateway
      - ./libs/common:/app/libs/common
    command: >
      sh -c "uvicorn apps.api_gateway.src.api_gateway.main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging: *default-logging
    networks:
      - taskflow-network
      
  user_service:
    build:
      context: .
      dockerfile: ./docker/python-service.Dockerfile
      args:
        APP_NAME: user_service
    container_name: taskflow-user-service
    ports:
      - "8001:8000"
    environment:
      <<: *common-env
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@postgres:5432
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./apps/user_service:/app/apps/user_service
      - ./libs/common:/app/libs/common
    command: >
      sh -c "
        cd /app/apps/user_service && 
        alembic upgrade head && 
        uvicorn apps.user_service.src.user_service.main:app --host 0.0.0.0 --port 8000 --reload
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging: *default-logging
    networks:
      - taskflow-network

  task_service:
    build:
      context: .
      dockerfile: ./docker/python-service.Dockerfile
      args:
        APP_NAME: task_service
    container_name: taskflow-task-service
    ports:
      - "8002:8000"
    environment:
      <<: *common-env
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@postgres:5432
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user_service:
        condition: service_healthy
    volumes:
      - ./apps/task_service:/app/apps/task_service
      - ./libs/common:/app/libs/common
    command: >
      sh -c "
        cd /app/apps/task_service && 
        alembic upgrade head && 
        uvicorn apps.task_service.src.task_service.main:app --host 0.0.0.0 --port 8000 --reload
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging: *default-logging
    networks:
      - taskflow-network

  notification_service:
    build:
      context: .
      dockerfile: ./docker/python-service.Dockerfile
      args:
        APP_NAME: notification_service
    container_name: taskflow-notification-service
    ports:
      - "8003:8000"
    environment:
      <<: *common-env
      DATABASE_URL: postgres://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@postgres:5432/notification_service
      NOTIFICATION_QUEUE_NAME: ${NOTIFICATION_QUEUE_NAME:-notifications}
      SMTP_HOST: ${SMTP_HOST:-smtp.mail.ru}
      SMTP_PORT: ${SMTP_PORT:-465}
      SMTP_USERNAME: ${SMTP_USERNAME:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL:-}
      SMTP_USE_TLS: ${SMTP_USE_TLS:-True}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_DB: ${REDIS_DB:-0}
    depends_on:
      redis:
        condition: service_healthy
      task_service:
        condition: service_healthy
      user_service:
        condition: service_healthy
    volumes:
      - ./apps/notification_service:/app/apps/notification_service
      - ./libs/common:/app/libs/common
    command: >
      sh -c "uvicorn apps.notification_service.src.notification_service.main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging: *default-logging
    networks:
      - taskflow-network

  analytics_service:
    build:
      context: .
      dockerfile: ./docker/python-service.Dockerfile
      args:
        APP_NAME: analytics_service
    container_name: taskflow-analytics-service
    ports:
      - "8004:8000"
    environment:
      <<: *common-env
      DATABASE_URL: postgres://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@postgres:5432/analytics_service
      AGGREGATION_PERIOD: ${AGGREGATION_PERIOD:-5}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      task_service:
        condition: service_healthy
      user_service:
        condition: service_healthy
    volumes:
      - ./apps/analytics_service:/app/apps/analytics_service
      - ./libs/common:/app/libs/common
    command: >
      sh -c "uvicorn apps.analytics_service.src.analytics_service.main:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging: *default-logging
    networks:
      - taskflow-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local


networks:
  taskflow-network:
    driver: bridge