"""make author_id nullable

Revision ID: fcb29e0c1e5f
Revises: 92f7be1ee498
Create Date: 2026-03-05 17:28:49.986933

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcb29e0c1e5f"
down_revision: Union[str, Sequence[str], None] = "92f7be1ee498"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "author_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "author_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
